### ISSUE TITLE
How to use TCP source to consume ADS-B data shared by adshub？

### ISSUE THREAD

**Issue by ten2net** [siddhi-io/siddhi-io-tcp#55]
**Description:**
 expect to consume ADS-B data published by data.adshub.org using TCP source. After configuring the server, I get the following error prompt:
```shell
Error starting Siddhi App 'ADSBDataPreprocessing', triggering shutdown process. Cannot assign requested address: bind
```

There is an ADS-B data source. Please refer to http://www.adshub.org/howtogetdata.php

**Suggested Labels:**
tcp,source,ads-b
My siddhi App:
```sql
@Source(type = 'tcp',
        context='/',
        @map(type='binary'))
define stream SmartHomeStream (id string);

@sink(type='log')
define stream ProcessedStream (id string);

--Process smart home data by concatenating the IDs and formatting the time
@info(name='query1')
from SmartHomeStream
select *
insert into ProcessedStream;
```
my tcp extension config:
```yaml
extensions:
  - extension:
      name: tcp
      namespace: source
      properties:
        host: data.adsbhub.org
        port: 5002
```
